site_name: Afero Developer Portal
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: green
markdown_extensions:
  - admonition
  - toc:       
      toc_depth: '2-2'
      permalink: true
